---

port: 4000
host: 0.0.0.0
safe: false


### site serving configuration ###
exclude: [CNAME, README.md, .gitignore]
timezone: null
lsi: false
highlighter: rouge


### content configuration ###
title:       "Horizon &mdash; Reflection done right"
keywords:    "C#, Horizon, Late Binding, Invoke, Reflection"
description: ".NET Fast Very Late Binding invoker"
source_link: "https://github.com/StevenThuriot/Horizon"
favicon:     #put a path like: "img/favicon.ico"
touch_icon:  #put a path like: "img/apple-touch-icon.png"
google_analytics_key: ## put YOUR key here to enable tracking! (blank to disable)


### template colors, used site-wide via css ###
colors:
  black:      '#111111'
  white:      '#f8f8f8'
  blue:       '#49a7e9'
  green:      '#9bcf2f'
  darkgreen:  '#228B22'
  purple:     '#c869bf'
  orange:     '#fab125'
  turquoise:  '#0fbfcf'
  darkorange: '#f27935'
  slategray:  '#708090'
